export const doctor = [
  {
    name: "Arun",
    contact: "9479412290",
    email: "arun@gmail.com",
    experience: "2 Years",
    rating: "4.0",
    price: "200",
    specialization: "Heart",
  },
  {
    name: "Arun",
    contact: "9479412290",
    email: "arun@gmail.com",
    experience: "2 Years",
    rating: "4.0",
    price: "200",
    specialization: "Heart",
  },
  {
    name: "Arun",
    contact: "9479412290",
    email: "arun@gmail.com",
    experience: "2 Years",
    rating: "4.0",
    price: "200",
    specialization: "Heart",
  },
  {
    name: "Arun",
    contact: "9479412290",
    email: "arun@gmail.com",
    experience: "2 Years",
    rating: "4.0",
    price: "200",
    specialization: "Heart",
  },
  {
    name: "Arun",
    contact: "9479412290",
    email: "arun@gmail.com",
    experience: "2 Years",
    rating: "4.0",
    price: "200",
    specialization: "Heart",
  },
  {
    name: "Arun",
    contact: "9479412290",
    email: "arun@gmail.com",
    experience: "2 Years",
    rating: "4.0",
    price: "200",
    specialization: "Heart",
  },
];
